name: Update Readme

on:
  schedule:
    - cron: '0 0 * * *' # Runs every night at midnight
  workflow_dispatch: # Allows you to run it manually

jobs:
  markscribe:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Update README.md
        uses: muesli/readme-scribe@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        with:
          template: 'templates/README.md.tpl'
          writeTo: 'README.md'
          
      - name: Commit & Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update markscribe stats
